/* DO NOT EDIT -- generated by Devel::CallChecker version 0.003 */
#ifndef xAd8NP3gxZglovQRL5Hn_INCLUDED
#define xAd8NP3gxZglovQRL5Hn_INCLUDED 1
#ifndef PERL_VERSION
 #error you must include perl.h before callchecker0.h
#elif !(PERL_REVISION == 5 && PERL_VERSION == 14 && PERL_SUBVERSION == 1)
 #error this callchecker0.h is for Perl 5.14.1 only
#endif /* Perl version mismatch */
#endif /* !xAd8NP3gxZglovQRL5Hn_INCLUDED */
